#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

run-docker-autopkgtest() {
  docker build --tag "privleap-test-docker:latest" .
  docker run -t --rm --privileged privleap-test-docker:latest 'setpriv --reuid $(id -u user) --regid $(id -g user) --init-groups --reset-env -- /home/user/privleap/run_autopkgtest'
  docker rmi privleap-test-docker:latest
}

run-docker-autopkgtest
