name: autopkgtest
on:
  push

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: ./docker_run_autopkgtest
        name: "Test privleap on Debian trixie"
